# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nnetwork <- function(X, Y, W1, W2, b1, b2, n_iter, learningrate) {
    .Call('nnetwork_nnetwork', PACKAGE = 'nnetwork', X, Y, W1, W2, b1, b2, n_iter, learningrate)
}

